Repository hanaro4-dIA/dia_pb_fe, pull requests merged in 2024-11, with the labels that each got.

#74 [feat] : NavigationBtn(네비게이션 버튼) 추가
  package.json
  pnpm-lock.yaml
  src/assets/NavigationBtn1.png
  src/assets/NavigationBtn2.png
  src/components/NavigationBtn.tsx
  src/main.tsx
Labels: develop

#82 [feat] : 손님 정보 페이지 arrowDrop 추가
  src/components/CustomerInformation.tsx
Labels: develop

#84 Feature/notiHistory
  src/components/NotiHistory.tsx
Labels: develop

#85 상담일지 리스트 영역 내 검색기능 추가
  src/components/ConsultationJournalList.tsx
  src/components/GuestList.tsx
  src/components/NotiHistory.tsx
  src/components/SearchField.tsx
  src/pages/DictionaryPage.tsx
Labels: develop

#87 Feature/search field
  public/data/Journals.json
  src/components/ConsultationJournalList.tsx
  src/components/GuestList.tsx
  src/components/SearchField.tsx
  src/pages/CustomerDetailPage.tsx
  src/pages/DictionaryPage.tsx
  src/pages/MainPage.tsx
Labels: bug, enhancement

#88 notificationPage 생성
  src/App.tsx
  src/components/NotiHistory.tsx
  src/components/WriteNoti.tsx
  src/pages/NotificationPage.tsx
Labels: enhancement

#90 Feature/consultation journal list item
  src/components/ConsultationJournalList.tsx
Labels: develop

#92 Feature/journal
  src/assets/mockupScript.png
  src/components/ConsultationJournalList.tsx
  src/components/MakeJournal.tsx
  src/components/ReadJournal.tsx
Labels: enhancement

#94 [feat] : 쪽지 상세보기 기능 추가, notification type 정리
  public/data/Notifications.json
  src/components/NotiHistory.tsx
  src/lib/types.ts
  src/pages/NotificationDetailsPage.tsx
Labels: enhancement

#108 Feature/iterating item component
  public/data/Dictionary.ts
  src/components/IteratingListItem.tsx
  src/components/NotiHistory.tsx
  src/containers/ConsultationJournalList.tsx
  src/containers/DictionaryDetail.tsx
  src/containers/DictionaryList.tsx
  src/containers/GuestList.tsx
  src/containers/NotificationHistory.tsx
  src/containers/WriteNotification.tsx
  src/lib/types.ts
  src/pages/DictionaryPage.tsx
  src/pages/NotificationDetailsWindow.tsx
  src/pages/NotificationPage.tsx
  src/pages/ReadJournalWindow.tsx
Labels: develop

#116 Feature/search debounce
  public/data/Dictionary.ts
  src/components/ConsultationJournalListItem.tsx
  src/components/IteratingListItem.tsx
  src/components/NavigationBtn.tsx
  src/components/RequestedConsultationItem.tsx
  src/components/Section.tsx
  src/components/UpcomingConsultationItem.tsx
  src/components/ui/accordion.tsx
  src/components/ui/button.tsx
  src/components/ui/input.tsx
  src/components/ui/label.tsx
  src/components/ui/switch.tsx
  src/containers/ConsultationJournalList.tsx
  src/containers/ConsultationRequest.tsx
  src/containers/CustomerInformation.tsx
  src/containers/DictionaryDetail.tsx
  src/containers/DictionaryList.tsx
  src/containers/GuestList.tsx
  src/containers/NotificationHistory.tsx
  src/containers/PbCalendar.tsx
  src/containers/PbProfile.tsx
  src/containers/ScheduledConsultationList.tsx
  src/hooks/useDebounce.tsx
  src/pages/ConsultingPage.tsx
  src/pages/CustomerDetailPage.tsx
  src/pages/DictionaryPage.tsx
  src/pages/MainPage.tsx
  src/pages/NotificationDetailsWindow.tsx
  src/pages/ReadJournalWindow.tsx
  src/types/componentTypes.ts
  src/types/dataTypes.ts
  src/utils/design-util.ts
  src/utils/getOffice-util.ts
  src/utils/remainingTime-util.tsx
Labels: develop

#120 Feature/session
  public/data/PB.json
  src/App.css
  src/App.tsx
  src/assets/diA_business.png
  src/assets/logo.png
  src/assets/notFound.gif
  src/components/Section.tsx
  src/containers/Login.tsx
  src/containers/PbProfile.tsx
  src/hooks/session-context.tsx
  src/hooks/sessionContext.tsx
  src/main.tsx
  src/pages/LoginPage.tsx
  src/pages/NotFoundPage.tsx
  src/types/dataTypes.ts
Labels: enhancement
