Repository hanaro4-dIA/dia_pb_fe, pull requests merged in 2024-12, with the labels that each got.

#125 Feature/column names, isLogin
  public/data/PB.json
  src/App.tsx
  src/assets/dIA_business_logo.png
  src/components/IteratingListItem.tsx
  src/containers/GuestList.tsx
  src/containers/Login.tsx
  src/containers/PbProfile.tsx
  src/hooks/sessionContext.tsx
  src/pages/LoginPage.tsx
  src/pages/NotFoundPage.tsx
  src/types/dataTypes.ts
Labels: bug, help wanted

#133 Feature/json data change
  public/data/Consultings.json
  public/data/Customer_PB.json
  public/data/Customers.json
  public/data/Dictionary.ts
  public/data/Notifications.json
  public/data/PB.json
  public/data/sample.json
  src/assets/diA_business.png
  src/components/RequestedConsultationItem.tsx
  src/components/UpcomingConsultationItem.tsx
  src/containers/ConsultationJournalList.tsx
  src/containers/ConsultationRequest.tsx
  src/containers/CustomerInformation.tsx
  src/containers/DictionaryDetail.tsx
  src/containers/GuestList.tsx
  src/containers/MakeJournal.tsx
  src/containers/NotificationHistory.tsx
  src/containers/PbCalendar.tsx
  src/containers/ScheduledConsultationList.tsx
  src/containers/WriteNotification.tsx
  src/pages/ConsultingPage.tsx
  src/pages/CustomerDetailPage.tsx
  src/pages/LoginPage.tsx
  src/pages/MainPage.tsx
  src/pages/NotFoundPage.tsx
  src/pages/ReadJournalWindow.tsx
  src/types/dataTypes.ts
  src/utils/remainingTime-util.tsx
  src/utils/types
  tsconfig.app.tsbuildinfo
  tsconfig.node.tsbuildinfo
Labels: develop

#137 Feature/storybook
  .storybook/main.ts
  .storybook/preview.ts
  package.json
  pnpm-lock.yaml
  src/components/ConsultationJournalListItem.tsx
  src/components/NavigationBtn.tsx
  src/components/RequestedConsultationItem.tsx
  src/components/Section.tsx
  src/components/UpcomingConsultationItem.tsx
  src/containers/ConsultationJournalList.tsx
  src/containers/ScheduledConsultationList.tsx
  src/hooks/sessionContext.tsx
  src/stories/Button.stories.ts
  src/stories/Button.tsx
  src/stories/Configure.mdx
  src/stories/CounsultationJournalListItem.stories.tsx
  src/stories/Header.stories.ts
  src/stories/Header.tsx
  src/stories/IteratingListItem.stories.tsx
  src/stories/NavigationBtn.stories.tsx
  src/stories/Page.stories.ts
  src/stories/Page.tsx
  src/stories/RequestedConsultationItem.stories.tsx
  src/stories/SearchField.stories.tsx
  src/stories/Section.stories.tsx
  src/stories/UpcomingConsultationItem.stories.tsx
  src/stories/assets/accessibility.png
  src/stories/assets/accessibility.svg
  src/stories/assets/addon-library.png
  src/stories/assets/assets.png
  src/stories/assets/avif-test-image.avif
  src/stories/assets/context.png
  src/stories/assets/discord.svg
  src/stories/assets/docs.png
  src/stories/assets/figma-plugin.png
  src/stories/assets/github.svg
  src/stories/assets/share.png
  src/stories/assets/styling.png
  src/stories/assets/testing.png
  src/stories/assets/theming.png
  src/stories/assets/tutorials.svg
  src/stories/assets/youtube.svg
  src/stories/button.css
  src/stories/header.css
  src/stories/page.css
  tsconfig.app.tsbuildinfo
  tsconfig.json
  vite.config.ts
Labels: enhancement

#139 Feature/scroll in customer list
  src/containers/CustomerList.tsx
  src/pages/CustomerDetailPage.tsx
  src/pages/MainPage.tsx
Labels: enhancement

#141 Feature/fix remaining time util
  public/data/Consultings.json
  src/types/dataTypes.ts
  src/utils/remainingTime-util.tsx
  src/utils/types
Labels: bug

#143 Feature/change consulting page UI
  src/containers/ConsultationScript.tsx
  src/containers/MakeJournal.tsx
  src/containers/Stt.tsx
  src/pages/ConsultingPage.tsx
Labels: develop

#146 Feature/get/pb/requested reserves
  .gitignore
  package.json
  pnpm-lock.yaml
  src/components/ApprovedConsultationItem.tsx
  src/components/RequestedConsultationItem.tsx
  src/containers/ApprovedConsultationsList.tsx
  src/containers/ConsultationRequest.tsx
  src/containers/PbCalendar.tsx
  src/containers/RequestedConsultationsList.tsx
  src/containers/ScheduledConsultationList.tsx
  src/hooks/useFetch.tsx
  src/pages/CustomerDetailPage.tsx
  src/pages/MainPage.tsx
  src/stories/UpcomingConsultationItem.stories.tsx
  src/types/dataTypes.ts
  src/utils/changeDateFormat-util.tsx
Labels: API 연결

#149 [feat] : 예정된 상담 일정 조회에 관한 api 연결 성공
  src/components/ApprovedConsultationItem.tsx
  src/containers/ApprovedConsultationsList.tsx
Labels: API 연결

#153 Feature/get/pb/customers/list
  public/data/Customers.json
  src/containers/CustomerList.tsx
Labels: API 연결

#155 Feature/get/pb/customer info
  src/containers/CustomerInformation.tsx
Labels: API 연결

#161 [feat] : 로그인 api 연결
  src/App.tsx
  src/containers/Login.tsx
  src/containers/PbProfile.tsx
  src/hooks/sessionContext.tsx
  src/hooks/useFetch.tsx
  src/types/dataTypes.ts
Labels: API 연결

#162 Feature/get/pb/profile
  src/containers/PbProfile.tsx
  src/types/dataTypes.ts
Labels: API 연결

#164 [feat] : pb/notifications에 대한 GET api 추가 (3개)
  src/containers/NotificationHistory.tsx
  src/pages/NotificationDetailsWindow.tsx
  src/types/dataTypes.ts
Labels: API 연결

#166 Feature/put/pb/approve reserve
  src/assets/clearAllRequests.gif
  src/components/RequestedConsultationItem.tsx
  src/containers/ApprovedConsultationsList.tsx
  src/containers/CustomerList.tsx
  src/containers/DictionaryDetail.tsx
  src/containers/PbProfile.tsx
  src/containers/RequestedConsultationsList.tsx
  src/hooks/consultationsContext.tsx
  src/hooks/useFetch.tsx
  src/pages/MainPage.tsx
Labels: API 연결

#167 Feature/post/pb/notifications/send
  src/containers/WriteNotification.tsx
  src/hooks/useFetch.tsx
Labels: API 연결

#169 [feat] : [POST] pb/customers/{{customerId}}/memo로 해당 손님에 대한 메모를 수정하게 변경
  src/containers/CustomerInformation.tsx
Labels: API 연결

#171 Feature/get/pb/keywords @KyoungEun-creator
  public/data/Dictionary.ts
  src/containers/ApprovedConsultationsList.tsx
  src/containers/CustomerList.tsx
  src/containers/DictionaryDetail.tsx
  src/containers/DictionaryList.tsx
  src/containers/PbProfile.tsx
  src/containers/RequestedConsultationsList.tsx
  src/hooks/useFetch.tsx
  src/pages/DictionaryPage.tsx
  src/types/componentTypes.ts
  src/types/dataTypes.ts
Labels: API 연결

#175 [feat] : 상담 일지 리스트 조회와 상담 일지를 클릭하면 나오는 내용들을 연결하였습니다.
  src/components/ConsultationJournalListItem.tsx
  src/containers/ConsultationJournalList.tsx
  src/pages/ReadJournalWindow.tsx
  src/types/dataTypes.ts
Labels: API 연결

#177 Feature/get/put/consultations
  src/components/ApprovedConsultationItem.tsx
  src/components/ConsultationJournalListItem.tsx
  src/components/IteratingListItem.tsx
  src/components/RequestedConsultationItem.tsx
  src/containers/ApprovedConsultationsList.tsx
  src/containers/ConsultationJournalList.tsx
  src/containers/CustomerInformation.tsx
  src/containers/CustomerList.tsx
  src/containers/Login.tsx
  src/containers/NotificationHistory.tsx
  src/containers/PbCalendar.tsx
  src/containers/PbProfile.tsx
  src/containers/RequestedConsultationsList.tsx
  src/containers/WriteNotification.tsx
  src/hooks/consultationsContext.tsx
  src/hooks/useFetch.tsx
  src/main.tsx
  src/pages/ConsultingPage.tsx
  src/pages/CustomerDetailPage.tsx
  src/pages/MainPage.tsx
  src/pages/NotificationDetailsWindow.tsx
  src/pages/ReadJournalWindow.tsx
  src/types/componentTypes.ts
  src/types/dataTypes.ts
Labels: bug, API 연결

#179 [feat] : 요청 내용 자세히보기 api 연결
  src/containers/MakeJournal.tsx
  src/pages/RequestContentPage.tsx
Labels: API 연결

#184 [feat] : 상담 일지 저장 추가(추천 상품 제외)
  src/containers/MakeJournal.tsx
Labels: API 연결

#186 [feat] : calendar 전체 일정 조회, 특정 날짜 일정 조회 api 연결
  src/containers/PbCalendar.tsx
Labels: API 연결

#189 Feature/get/pb/journals/products
  src/components/JournalProductInputArea.tsx
  src/containers/ApprovedConsultationsList.tsx
  src/containers/ConsultationJournalList.tsx
  src/containers/MakeJournal.tsx
  src/pages/ReadJournalWindow.tsx
  src/pages/RequestContentPage.tsx
  src/types/dataTypes.ts
Labels: API 연결

#191 Feature/post/pb/logout
  src/App.tsx
  src/components/JournalProductInputArea.tsx
  src/components/RequestedConsultationItem.tsx
  src/containers/ApprovedConsultationsList.tsx
  src/containers/ConsultationJournalList.tsx
  src/containers/CustomerInformation.tsx
  src/containers/CustomerList.tsx
  src/containers/Login.tsx
  src/containers/MakeJournal.tsx
  src/containers/NotificationHistory.tsx
  src/containers/PbCalendar.tsx
  src/containers/PbProfile.tsx
  src/containers/RequestedConsultationsList.tsx
  src/containers/WriteNotification.tsx
  src/hooks/sessionContext.tsx
  src/hooks/useFetch.tsx
  src/main.tsx
  src/pages/ConsultingPage.tsx
  src/pages/CustomerDetailPage.tsx
  src/pages/DictionaryPage.tsx
  src/pages/NotificationDetailsWindow.tsx
  src/pages/ReadJournalWindow.tsx
  src/pages/RequestContentPage.tsx
Labels: API 연결

#187 Feature/pb/profile (태그, 한줄소개, 프로필 수정 가능)
  src/containers/PbProfile.tsx
Labels: API 연결

#194 [fix] : 쪽지 전송 관련, url 수정
  src/containers/WriteNotification.tsx
Labels: bug

#197 Feature/pb/journals
  src/components/ApprovedConsultationItem.tsx
  src/containers/ConsultationScript.tsx
  src/containers/MakeJournal.tsx
  src/pages/ConsultingPage.tsx
Labels: API 연결

#199 [fix] 캘린더 api 수정
  src/containers/PbCalendar.tsx
Labels: bug

#195 [feat] : 상담 일지 전송 기능 연결
  src/components/JournalProductInputArea.tsx
  src/containers/MakeJournal.tsx
  src/pages/RequestContentPage.tsx
Labels: API 연결

#204 [fix] : script 높이 자동 조절 및 text 변경 가능하게 작업
  src/containers/ConsultationScript.tsx
Labels: API 연결

#205 Feature/fix get put consultings
  src/App.tsx
  src/components/ApprovedConsultationItem.tsx
  src/components/JournalProductInputArea.tsx
  src/components/RequestedConsultationItem.tsx
  src/containers/ApprovedConsultationsList.tsx
  src/containers/ConsultationJournalList.tsx
  src/containers/CustomerList.tsx
  src/containers/MakeJournal.tsx
  src/containers/NotificationHistory.tsx
  src/containers/PbCalendar.tsx
  src/containers/RequestedConsultationsList.tsx
  src/hooks/useFetch.tsx
  src/pages/ConsultingPage.tsx
  src/pages/CustomerDetailPage.tsx
  src/pages/MainPage.tsx
  src/pages/NotificationDetailsWindow.tsx
  src/pages/ReadJournalWindow.tsx
  src/pages/RequestContentPage.tsx
  src/stories/RequestedConsultationItem.stories.tsx
  src/utils/remainingTime-util.tsx
  tsconfig.app.tsbuildinfo
Labels: API 연결

#206 [feat] : put api 연결 - 스크립트 수정
  src/containers/ConsultationScript.tsx
Labels: API 연결

#209 Feature/pb/calendar/category
  src/containers/PbCalendar.tsx
  src/types/dataTypes.ts
Labels: bug, API 연결

#212 Feature/post/pb/journals
  package.json
  pnpm-lock.yaml
  src/components/JournalProductInputArea.tsx
  src/containers/ConsultationScript.tsx
  src/containers/MakeJournal.tsx
  src/pages/ConsultingPage.tsx
Labels: API 연결

#211 [feat] : 스크립트 삭제 기능 추가
  src/containers/ConsultationScript.tsx
Labels: develop, API 연결

#213 [fix] : 스크립트 delete 한 것이 바로 반영되도록 filter 사용
  src/containers/ConsultationScript.tsx
Labels: API 연결

#216 [feat] : 상담일지가 complete:true만 보이게끔 추가
  src/components/ConsultationJournalListItem.tsx
  src/types/dataTypes.ts
Labels: bug, API 연결

#220 [feat] : 전체선택의 기능이 필터링과 관계없이 전체 선택이 되게끔 수정
  src/containers/NotificationHistory.tsx
  src/containers/WriteNotification.tsx
Labels: develop

#224 Feature/fix accept consultations
  public/data/Category.json
  public/data/Consultings.json
  public/data/Journals.json
  public/data/Notifications.json
  public/data/PB.json
  src/containers/ApprovedConsultationsList.tsx
  src/containers/MakeJournal.tsx
  src/containers/PbCalendar.tsx
  src/containers/PbProfile.tsx
  src/containers/RequestedConsultationsList.tsx
  src/hooks/useFetch.tsx
  src/main.tsx
  src/pages/ConsultingPage.tsx
  src/pages/MainPage.tsx
Labels: bug, API 연결
